import { type Project } from "@/components/dashboard/project-card";

export const DUMMY_PROJECTS: Project[] = [
  {
    id: "1",
    name: "Internal API Platform",
    description: "Modernizing our internal gateway with high-performance edge computing and unified authentication.",
    status: "active",
    health: 45,
    healthStatus: "At Risk",
    concernsCount: 12,
    achievementsCount: 8,
    team: [
      "https://i.pravatar.cc/150?u=1",
      "https://i.pravatar.cc/150?u=2",
      "https://i.pravatar.cc/150?u=3",
      "https://i.pravatar.cc/150?u=4",
      "https://i.pravatar.cc/150?u=5",
    ],
  },
  {
    id: "2",
    name: "Security Audit 2026",
    description: "Comprehensive review of all data-at-rest and in-transit protocols for the upcoming compliance cycle.",
    status: "planning",
    health: 90,
    healthStatus: "Stable",
    concernsCount: 0,
    achievementsCount: 3,
    team: [
      "https://i.pravatar.cc/150?u=10",
      "https://i.pravatar.cc/150?u=11",
    ],
  },
  {
    id: "3",
    name: "Dashboard UI Revamp",
    description: "Shifting our admin interface to a more fluid, component-based architecture with better accessibility.",
    status: "completed",
    health: 100,
    healthStatus: "Stable",
    concernsCount: 2,
    achievementsCount: 15,
    team: [
      "https://i.pravatar.cc/150?u=20",
      "https://i.pravatar.cc/150?u=21",
      "https://i.pravatar.cc/150?u=22",
    ],
  },
  {
    id: "4",
    name: "Cross-platform Mobile App",
    description: "Building the next-gen Signal mobile companion using React Native and shared business logic layers.",
    status: "on-hold",
    health: 20,
    healthStatus: "Critical",
    concernsCount: 24,
    achievementsCount: 5,
    team: [
      "https://i.pravatar.cc/150?u=30",
      "https://i.pravatar.cc/150?u=31",
      "https://i.pravatar.cc/150?u=32",
      "https://i.pravatar.cc/150?u=33",
    ],
  },
];
